[class]
image_default = [
    { command = "sxiv", fork = true, silent = true } ]
video_default = [
    { command = "mpv", fork = true, silent = true } ]
audio_default = [
    { command = "mplayer"} ]
spreadsheet_default = [
    { command = "gnumeric", fork = true, silent = true } ]

[extension]
# images
png.inherit = "image_default"
jpg.inherit = "image_default"

# video
mkv.inherit = "video_default"
webm.inherit = "video_default"
mp4.inherit = "video_default"

# audio
mp3.inherit = "audio_default"
wav.inherit = "audio_default"
WAV.inherit = "audio_default"

# spreadsheets
xls.inherit = "spreadsheet_default"
xlsx.inherit = "spreadsheet_default"
gnumeric.inherit = "spreadsheet_default"

pdf.app_list = [
             { command = "zathura", fork = true, silent = true },
             { command = "llpp", fork = true, silent = true },
             { command = "mupdf", fork = true, silent = true } ]
