#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5
bspc config bottom_padding       25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Next state=tiled

# autostart
# ==============================================================================

sxhkd &
#xrdb -merge $HOME/.Xresources
. $HOME/.config/polybar/launch.sh

# manage wallpaper
if [ -x /usr/bin/feh ]; then
    feh --bg-scale /home/iwaka/dotfiles/wallpapers/wp3.jpg
fi

# display compositor
if [ -x /usr/bin/compton ]; then
    compton -bf &
fi

if [ -x /usr/bin/devmon ]; then
    devmon &
fi

if [ -x /usr/bin/unclutter ]; then
    unclutter &
fi

if [ -x /usr/bin/fcitx ]; then
    fcitx &
fi

if [ -x /usr/bin/dropbox ]; then
    dropbox &
fi

