#! /bin/fish

# A wrapper to launch various programs if they're not
# already running.
function run
    pgrep -x $argv[1] > /dev/null; or $argv
end

function launch-polybar
    # Terminate already running bar instances
    killall -q polybar
    # Wait until the processes have been shut down
    while pgrep -u $UID -x polybar > /dev/null
        sleep 1
    end
    # Launch Polybar using default config location
    polybar example &
end

run sxhkd
launch-polybar
run compton -bf
run fcitx
run devmon
run dropbox
run unclutter
feh --bg-scale /home/iwaka/dotfiles/wallpapers/wp3.jpg

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

