#! /bin/sh

sxhkd &
~/.config/polybar/launch.sh
fcitx &
devmon &
dropbox &
unclutter &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

